# Generated by Django 5.1.1 on 2024-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_chain', models.CharField(max_length=255)),
                ('ref_no', models.CharField(max_length=100)),
                ('tender_id', models.CharField(max_length=100)),
            ],
        ),
    ]
