# Generated by Django 5.1.1 on 2024-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='zip_url',
            field=models.URLField(null=True),
        ),
    ]
